ALTER TABLE users ADD COLUMN Sex VARCHAR(20);
ALTER TABLE users ADD COLUMN Weight VARCHAR(20);
ALTER TABLE users ADD COLUMN Height VARCHAR(20);

ALTER TABLE users ADD COLUMN Medications TEXT;
ALTER TABLE users ADD COLUMN Allergies TEXT;
ALTER TABLE users ADD COLUMN Active_Problems TEXT;
ALTER TABLE users ADD COLUMN Medical_History TEXT;
ALTER TABLE users ADD COLUMN Family_History TEXT;

ALTER TABLE users ADD COLUMN Date_Updated DATETIME;